[theme]
primaryColor = "#FF8C00"
backgroundColor = "#FFFAF0"
secondaryBackgroundColor = "#FFF4E6"
textColor = "#2C1810"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[global]
developmentMode = false
