[spotify]
client_id = "REPLACE_WITH_CLIENT_ID"
client_secret = "REPLACE_WITH_CLIENT_SECRET"
# redirect_uri = "https://your-app.streamlit.app/"  # Optional: Uncomment and set for production

[youtube]
api_key = "REPLACE_WITH_API_KEY"